-- AlterTable
ALTER TABLE "ThreadComment" ADD COLUMN     "mediaUrls" JSONB NOT NULL DEFAULT '[]',
ALTER COLUMN "mediaUrl" DROP NOT NULL,
ALTER COLUMN "mediaUrl" DROP DEFAULT,
ALTER COLUMN "mediaUrl" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "ThreadReply" ADD COLUMN     "mediaUrls" JSONB NOT NULL DEFAULT '[]',
ALTER COLUMN "mediaUrl" DROP NOT NULL,
ALTER COLUMN "mediaUrl" DROP DEFAULT,
ALTER COLUMN "mediaUrl" SET DATA TYPE TEXT;
